# Generated by Django 4.0.3 on 2022-03-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_total_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='total_sales',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
