# Generated by Django 4.0.3 on 2022-03-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_total_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
