# Generated by Django 4.0.3 on 2022-03-29 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0006_alter_employee_total_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image_data',
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=employee.models.upload_to),
        ),
    ]
