# Generated by Django 4.0.3 on 2022-04-22 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_card',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reg_no',
            field=models.AutoField(primary_key=True, serialize=False, unique='True'),
        ),
    ]
